--
-- PostgreSQL database dump
--
-- Dumped from database version 13.2 (Debian 13.2-1.pgdg100+1)
-- Dumped by pg_dump version 13.2
-- Started on 2021-04-18 20:01:56 UTC
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;
--
-- TOC entry 213 (class 1259 OID 24709)
-- Name: adventure; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.adventure (
    id bigint NOT NULL,
    level integer NOT NULL,
    name character(40) NOT NULL,
    idmonster bigint NOT NULL
);
ALTER TABLE public.adventure OWNER TO postgres;
--
-- TOC entry 212 (class 1259 OID 24707)
-- Name: adventure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.adventure
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.adventure_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 222 (class 1259 OID 24821)
-- Name: aventure_monsters; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.aventure_monsters (monsterid bigint, adventureid bigint);
ALTER TABLE public.aventure_monsters OWNER TO postgres;
--
-- TOC entry 205 (class 1259 OID 24676)
-- Name: equip; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.equip (
    id bigint NOT NULL,
    name character(30) NOT NULL,
    level integer NOT NULL,
    type character(20) NOT NULL,
    defence integer,
    damage integer,
    price integer NOT NULL,
    sellprice integer NOT NULL
);
ALTER TABLE public.equip OWNER TO postgres;
--
-- TOC entry 204 (class 1259 OID 24674)
-- Name: equip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.equip
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.equip_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 217 (class 1259 OID 24736)
-- Name: hero; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.hero (
    id bigint NOT NULL,
    name character(30) NOT NULL,
    level integer NOT NULL,
    hptotal integer NOT NULL,
    hpactual integer NOT NULL,
    xp integer NOT NULL,
    levelmaxxp integer NOT NULL,
    gold integer NOT NULL,
    deaths integer NOT NULL,
    monsterskilled integer NOT NULL,
    idshield bigint,
    idweapon bigint,
    idplaystatus bigint,
    iddamageproficience bigint,
    iddefenceproficience bigint,
    idheroclass bigint
);
ALTER TABLE public.hero OWNER TO postgres;
--
-- TOC entry 216 (class 1259 OID 24734)
-- Name: hero_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.hero
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.hero_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 203 (class 1259 OID 24669)
-- Name: heroclass; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.heroclass (
    id bigint NOT NULL,
    name character(30) NOT NULL,
    damagebuff integer NOT NULL,
    shieldbuff integer NOT NULL,
    hpbuff integer NOT NULL,
    goldbuff integer NOT NULL,
    expbuff integer NOT NULL,
    attackspeedbuff integer NOT NULL
);
ALTER TABLE public.heroclass OWNER TO postgres;
--
-- TOC entry 202 (class 1259 OID 24667)
-- Name: heroclass_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.heroclass
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.heroclass_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 221 (class 1259 OID 24790)
-- Name: inventory_equip; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.inventory_equip (
    id bigint NOT NULL,
    idhero bigint,
    equiped boolean NOT NULL,
    idequip bigint
);
ALTER TABLE public.inventory_equip OWNER TO postgres;
--
-- TOC entry 220 (class 1259 OID 24788)
-- Name: inventory_equip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.inventory_equip
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.inventory_equip_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 219 (class 1259 OID 24773)
-- Name: inventory_potion; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.inventory_potion (
    id bigint NOT NULL,
    idhero bigint,
    amount integer NOT NULL,
    idpotion bigint
);
ALTER TABLE public.inventory_potion OWNER TO postgres;
--
-- TOC entry 218 (class 1259 OID 24771)
-- Name: inventory_potion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.inventory_potion
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.inventory_potion_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 201 (class 1259 OID 16386)
-- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.migrations (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying NOT NULL
);
ALTER TABLE public.migrations OWNER TO postgres;
--
-- TOC entry 200 (class 1259 OID 16384)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
CREATE SEQUENCE public.migrations_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.migrations_id_seq OWNER TO postgres;
--
-- TOC entry 3067 (class 0 OID 0)
-- Dependencies: 200
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--
ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;
--
-- TOC entry 209 (class 1259 OID 24690)
-- Name: monster; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.monster (
    id bigint NOT NULL,
    name character(30) NOT NULL,
    level integer NOT NULL,
    damage integer NOT NULL,
    hp integer NOT NULL,
    defence integer NOT NULL,
    givedxp integer NOT NULL,
    givedgold integer NOT NULL,
    equipdropchance integer NOT NULL,
    idequipdrop bigint
);
ALTER TABLE public.monster OWNER TO postgres;
--
-- TOC entry 208 (class 1259 OID 24688)
-- Name: monster_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.monster
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.monster_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 215 (class 1259 OID 24721)
-- Name: play_status; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.play_status (
    id bigint NOT NULL,
    task character(30),
    gold integer NOT NULL,
    monsterskilled integer DEFAULT 0 NOT NULL,
    exp integer DEFAULT 0 NOT NULL,
    timestarted integer DEFAULT 0 NOT NULL,
    idadventure bigint
);
ALTER TABLE public.play_status OWNER TO postgres;
--
-- TOC entry 214 (class 1259 OID 24719)
-- Name: play_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.play_status
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.play_status_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 211 (class 1259 OID 24702)
-- Name: potion; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.potion (
    id bigint NOT NULL,
    name character(50) NOT NULL,
    price integer NOT NULL,
    hpheal integer NOT NULL
);
ALTER TABLE public.potion OWNER TO postgres;
--
-- TOC entry 210 (class 1259 OID 24700)
-- Name: potion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.potion
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.potion_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 207 (class 1259 OID 24683)
-- Name: proficience; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.proficience (
    id bigint NOT NULL,
    level integer NOT NULL,
    xp integer NOT NULL,
    levelmaxxp integer NOT NULL
);
ALTER TABLE public.proficience OWNER TO postgres;
--
-- TOC entry 206 (class 1259 OID 24681)
-- Name: proficience_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.proficience
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.proficience_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- TOC entry 2868 (class 2604 OID 16389)
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.migrations
ALTER COLUMN id
SET DEFAULT nextval('public.migrations_id_seq'::regclass);
--
-- TOC entry 3052 (class 0 OID 24709)
-- Dependencies: 213
-- Data for Name: adventure; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.adventure (id, level, name, idmonster)
FROM stdin;
\.--
-- TOC entry 3061 (class 0 OID 24821)
-- Dependencies: 222
-- Data for Name: aventure_monsters; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.aventure_monsters (monsterid, adventureid)
FROM stdin;
\.--
-- TOC entry 3044 (class 0 OID 24676)
-- Dependencies: 205
-- Data for Name: equip; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.equip (
    id,
    name,
    level,
    type,
    defence,
    damage,
    price,
    sellprice
)
FROM stdin;
1 Bronze Short Sword 1 weapon \ N 6 6 3 2 Blunt Sword 2 weapon \ N 13 25 10 3 Reaper Scythe 3 weapon \ N 19 56 23 4 Bone Dagger 4 weapon \ N 25 100 40 5 Carnwennan 5 weapon \ N 31 156 63 6 Firelord Keyblade 6 weapon \ N 38 225 90 7 Candy Sword 7 weapon \ N 44 306 123 8 Rose Sword 8 weapon \ N 50 400 160 9 Iron Scimitar 9 weapon \ N 56 506 203 10 Iron Rapier 10 weapon \ N 63 625 250 11 Iron Mace 11 weapon \ N 69 756 303 12 Iron Flail 12 weapon \ N 75 900 360 13 Emerald Sabre 13 weapon \ N 81 1056 423 14 Oblivion Blade 14 weapon \ N 88 1225 490 15 Behemoth Slayer 15 weapon \ N 94 1406 563 16 Hrunting 16 weapon \ N 100 1600 640 17 Overlord Blade 17 weapon \ N 106 1806 723 18 The Devastator 18 weapon \ N 113 2025 810 19 Unicorn Blade 19 weapon \ N 119 2256 903 20 Fire Flail 20 weapon \ N 125 2500 1000 21 Acrimony 21 weapon \ N 131 2756 1103 22 Agony 22 weapon \ N 138 3025 1210 23 Azure Lightning 23 weapon \ N 144 3306 1323 24 Balance 24 weapon \ N 150 3600 1440 25 Blessed One 25 weapon \ N 156 3906 1563 26 Bone 26 weapon \ N 163 4225 1690 27 Bonnie ’ s Bounty 27 weapon \ N 169 4556 1823 28 Honor 28 'weapon             	\N	175	4900	1960
29	Orc Cleaver                   	29	weapon              	\N	181	5256	2103
30	Oracle                        	30	weapon              	\N	188	5625	2250
31	Winter’s Bane                 	31	weapon              	\N	194	6006	2403
32	Vengeance                     	32	weapon              	\N	200	6400	2560
33	Torrent                       	33	weapon              	\N	206	6806	2723
34	Zara’s Song                   	34	weapon              	\N	213	7225	2890
35	Scorned Woman                 	35	weapon              	\N	219	7656	3063
36	Obsession                     	36	weapon              	\N	225	8100	3240
37	Misery Sword                  	37	weapon              	\N	231	8556	3423
38	Quicksilver                   	38	weapon              	\N	238	9025	3610
39	Queen’s Rage                  	39	weapon              	\N	244	9506	3803
40	Severity                      	40	weapon              	\N	250	10000	4000
41	Splinter                      	41	weapon              	\N	256	10506	4203
42	Talon                         	42	weapon              	\N	263	11025	4410
43	Swagger                       	43	weapon              	\N	269	11556	4623
44	Tidal Wave                    	44	weapon              	\N	275	12100	4840
45	Unrepentant                   	45	weapon              	\N	281	12656	5063
46	Usurper’s Bane                	46	weapon              	\N	288	13225	5290
47	Valor                         	47	weapon              	\N	294	13806	5523
48	Vapor                         	48	weapon              	\N	300	14400	5760
49	Moonlight                     	49	weapon              	\N	306	15006	6003
50	Restored Ward                 	50	weapon              	\N	313	15625	6250
51	Stolen Fence                  	1	shield              	\N	6	9	4
52	Pan Lid                       	2	shield              	\N	13	38	15
53	Black Phoenix Shield          	3	shield              	\N	19	84	34
54	Mithril Buckler               	4	shield              	\N	25	150	60
55	Steel Shield                  	5	shield              	\N	31	234	94
56	Adamantium Shield             	6	shield              	\N	38	338	135
57	Skull Shield                  	7	shield              	\N	44	459	184
58	Wooden Legend Shield          	8	shield              	\N	50	600	240
59	Silver Legend Shield          	9	shield              	\N	56	759	304
60	Adamantium Legend Shield      	10	shield              	\N	63	938	375
61	Steel Ancient Shield          	11	shield              	\N	69	1134	454
62	Gold Ancient Shield           	12	shield              	\N	75	1350	540
63	Steel Aquila Shield           	13	shield              	\N	81	1584	634
64	Silver Aquila Shield          	14	shield              	\N	88	1838	735
65	Bronze Kalkan                 	15	shield              	\N	94	2109	844
66	Silver Kalkan                 	16	shield              	\N	100	2400	960
67	Gold Kalkan                   	17	shield              	\N	106	2709	1084
68	Crossheider                   	18	shield              	\N	113	3038	1215
69	Deimos Warrior Shield         	19	shield              	\N	119	3384	1354
70	Timeless Kite Shield          	20	shield              	\N	125	3750	1500
71	Blue Hoflon                   	21	shield              	\N	131	4134	1654
72	Battle Shield                 	22	shield              	\N	138	4538	1815
73	Triangular Shield             	23	shield              	\N	144	4959	1984
74	Timeless List                 	24	shield              	\N	150	5400	2160
75	Deimos Shadow Shield          	25	shield              	\N	156	5859	2344
76	Deimos Sage Shield            	26	shield              	\N	163	6338	2535
77	Timeless Prelude              	27	shield              	\N	169	6834	2734
78	Esther Shield                 	28	shield              	\N	175	7350	2940
79	Rattan                        	29	shield              	\N	181	7884	3154
80	Leather lamellar              	30	shield              	\N	188	8438	3375
81	Maille                        	31	shield              	\N	194	9009	3604
82	Lost Paradise                 	32	shield              	\N	200	9600	3840
83	Blind Hatred                  	33	shield              	\N	206	10209	4084
84	Reign Maker                   	34	shield              	\N	213	10838	4335
85	Wind' s Carapace 35 shield \ N 219 11484 4594 86 Defiled Redwood Light Shield 36 shield \ N 225 12150 4860 87 Vicious Armament 37 shield \ N 231 12834 5134 88 The Sentinel 38 shield \ N 238 13538 5415 89 Brutality Bastion 39 shield \ N 244 14259 5704 90 Shepherd 40 shield \ N 250 15000 6000 91 Unholy Aegis 41 shield \ N 256 15759 6304 92 Blackout 42 shield \ N 263 16538 6615 93 Mercy 43 shield \ N 269 17334 6934 94 Eulogy 44 shield \ N 275 18150 7260 95 Fragile Iron Shield 45 shield \ N 281 18984 7594 96 Warmonger 46 shield \ N 288 19838 7935 97 Peace Maker 47 shield \ N 294 20709 8284 98 Blind Hatred 48 shield \ N 300 21600 8640 99 Promised Tower Shield 49 shield \ N 306 22509 9004 100 Crazed Warpwood Keeper 50 shield \ N 313 23438 9375 \.--
-- TOC entry 3056 (class 0 OID 24736)
-- Dependencies: 217
-- Data for Name: hero; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.hero (
    id,
    name,
    level,
    hptotal,
    hpactual,
    xp,
    levelmaxxp,
    gold,
    deaths,
    monsterskilled,
    idshield,
    idweapon,
    idplaystatus,
    iddamageproficience,
    iddefenceproficience,
    idheroclass
)
FROM stdin;
\.--
-- TOC entry 3042 (class 0 OID 24669)
-- Dependencies: 203
-- Data for Name: heroclass; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.heroclass (
    id,
    name,
    damagebuff,
    shieldbuff,
    hpbuff,
    goldbuff,
    expbuff,
    attackspeedbuff
)
FROM stdin;
3 Begginner 0 0 0 0 0 0 4 Warrior 0 0 5 0 0 0 5 Mage 0 0 0 0 3 0 6 Thief 0 0 0 1 0 0 7 Archer 0 0 5 0 0 0 8 Knight 0 0 10 1 0 0 9 Paladin 5 0 5 1 0 0 10 Necro 0 0 5 0 0 0 11 Ladin 0 0 5 1 0 0 12 Ninja 5 0 0 1 0 0 13 Hunter 10 0 0 1 0 1 14 Trickster 5 0 5 1 0 1 \.--
-- TOC entry 3060 (class 0 OID 24790)
-- Dependencies: 221
-- Data for Name: inventory_equip; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.inventory_equip (id, idhero, equiped, idequip)
FROM stdin;
\.--
-- TOC entry 3058 (class 0 OID 24773)
-- Dependencies: 219
-- Data for Name: inventory_potion; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.inventory_potion (id, idhero, amount, idpotion)
FROM stdin;
\.--
-- TOC entry 3040 (class 0 OID 16386)
-- Dependencies: 201
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.migrations (id, "timestamp", name)
FROM stdin;
\.--
-- TOC entry 3048 (class 0 OID 24690)
-- Dependencies: 209
-- Data for Name: monster; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.monster (
    id,
    name,
    level,
    damage,
    hp,
    defence,
    givedxp,
    givedgold,
    equipdropchance,
    idequipdrop
)
FROM stdin;
2 Slime 1 5 30 1 1 1 0 \ N 3 Fang Rat 2 6 33 2 2 3 0 \ N 4 Harpy 3 7 36 3 3 5 0 \ N 5 Goblin 4 8 39 4 4 7 0 \ N 6 Zombie 5 9 42 5 5 9 0 \ N 7 Wisp 6 10 45 6 6 11 0 \ N 8 Scout 7 11 48 7 7 13 0 \ N 9 Rat 8 12 51 8 8 15 0 \ N 10 Driller 9 13 54 9 9 17 0 \ N 11 Sand Viper 10 14 57 10 10 19 0 \ N 12 Earthsoul 11 18 70 13 12 22 0 \ N 13 Horror Box 12 22 74 16 14 25 0 \ N 14 Eyeant 13 26 78 19 16 28 0 \ N 15 Watchman of Darkness 14 30 82 22 18 31 0 \ N 16 Fire - breathing Rat 15 34 86 25 20 34 0 \ N 17 Mandrake 16 38 90 28 22 37 0 \ N 18 Graveyard Watchman 17 42 94 31 24 40 0 \ N 19 Deathviper 18 46 98 34 26 43 0 \ N 20 Seeker 19 50 102 37 28 46 0 \ N 21 Devil Plant 20 54 106 40 30 49 0 \ N 22 Flame Wolf 21 59 111 44 32 53 0 \ N 23 Blue Gel 22 64 116 48 34 57 0 \ N 24 Crocodino 23 69 121 52 36 61 0 \ N 25 Demon Soul 24 74 126 56 38 65 0 \ N 26 High Driller 25 79 131 60 40 69 0 \ N 27 Stray Metaan 26 84 136 64 42 73 0 \ N 28 Looter 27 89 141 68 44 77 0 \ N 29 Sprite 28 94 146 72 46 81 0 \ N 30 Forest Watchman 29 99 151 76 48 85 0 \ N 31 Gobleader 30 104 156 80 50 89 0 \ N 32 Mage Goblin 31 109 161 84 52 93 0 \ N 33 Goblin Follower 32 114 166 88 54 97 0 \ N 34 Nymph 33 119 171 92 56 101 0 \ N 35 Ice Wolf 34 124 176 96 58 105 0 \ N 36 Wyvern 35 129 181 100 60 109 0 \ N 37 Death Box 36 134 186 104 62 113 0 \ N 38 DeathGator 37 139 191 108 64 117 0 \ N 39 Laprox 38 144 196 112 66 121 0 \ N 40 Hell Messenger 39 149 201 116 68 125 0 \ N 41 Jumper 40 154 206 120 70 129 0 \ N 42 Drillkiller 41 159 211 124 72 133 0 \ N 43 Mob Soldier 42 164 216 128 74 137 0 \ N 44 Gang Machine 43 169 221 132 76 141 0 \ N 45 Death Armor 44 174 226 136 78 145 0 \ N 46 Onigami 45 179 231 140 80 149 0 \ N 47 Inugami 46 184 236 144 82 153 0 \ N \.--
-- TOC entry 3054 (class 0 OID 24721)
-- Dependencies: 215
-- Data for Name: play_status; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.play_status (
    id,
    task,
    gold,
    monsterskilled,
    exp,
    timestarted,
    idadventure
)
FROM stdin;
\.--
-- TOC entry 3050 (class 0 OID 24702)
-- Dependencies: 211
-- Data for Name: potion; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.potion (id, name, price, hpheal)
FROM stdin;
\.--
-- TOC entry 3046 (class 0 OID 24683)
-- Dependencies: 207
-- Data for Name: proficience; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.proficience (id, level, xp, levelmaxxp)
FROM stdin;
\.--
-- TOC entry 3068 (class 0 OID 0)
-- Dependencies: 212
-- Name: adventure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.adventure_id_seq', 1, false);
--
-- TOC entry 3069 (class 0 OID 0)
-- Dependencies: 204
-- Name: equip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.equip_id_seq', 100, true);
--
-- TOC entry 3070 (class 0 OID 0)
-- Dependencies: 216
-- Name: hero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.hero_id_seq', 1, false);
--
-- TOC entry 3071 (class 0 OID 0)
-- Dependencies: 202
-- Name: heroclass_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.heroclass_id_seq', 14, true);
--
-- TOC entry 3072 (class 0 OID 0)
-- Dependencies: 220
-- Name: inventory_equip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.inventory_equip_id_seq', 1, false);
--
-- TOC entry 3073 (class 0 OID 0)
-- Dependencies: 218
-- Name: inventory_potion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.inventory_potion_id_seq', 1, false);
--
-- TOC entry 3074 (class 0 OID 0)
-- Dependencies: 200
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.migrations_id_seq', 1, false);
--
-- TOC entry 3075 (class 0 OID 0)
-- Dependencies: 208
-- Name: monster_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.monster_id_seq', 47, true);
--
-- TOC entry 3076 (class 0 OID 0)
-- Dependencies: 214
-- Name: play_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.play_status_id_seq', 1, false);
--
-- TOC entry 3077 (class 0 OID 0)
-- Dependencies: 210
-- Name: potion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.potion_id_seq', 1, false);
--
-- TOC entry 3078 (class 0 OID 0)
-- Dependencies: 206
-- Name: proficience_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--
SELECT pg_catalog.setval('public.proficience_id_seq', 1, false);
--
-- TOC entry 2873 (class 2606 OID 16394)
-- Name: migrations PK_8c82d7f526340ab734260ea46be; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.migrations
ADD CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id);
--
-- TOC entry 2885 (class 2606 OID 24713)
-- Name: adventure adventure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.adventure
ADD CONSTRAINT adventure_pkey PRIMARY KEY (id);
--
-- TOC entry 2877 (class 2606 OID 24680)
-- Name: equip equip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.equip
ADD CONSTRAINT equip_pkey PRIMARY KEY (id);
--
-- TOC entry 2889 (class 2606 OID 24740)
-- Name: hero hero_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_pkey PRIMARY KEY (id);
--
-- TOC entry 2875 (class 2606 OID 24673)
-- Name: heroclass heroclass_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.heroclass
ADD CONSTRAINT heroclass_pkey PRIMARY KEY (id);
--
-- TOC entry 2893 (class 2606 OID 24794)
-- Name: inventory_equip inventory_equip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.inventory_equip
ADD CONSTRAINT inventory_equip_pkey PRIMARY KEY (id);
--
-- TOC entry 2891 (class 2606 OID 24777)
-- Name: inventory_potion inventory_potion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.inventory_potion
ADD CONSTRAINT inventory_potion_pkey PRIMARY KEY (id);
--
-- TOC entry 2881 (class 2606 OID 24694)
-- Name: monster monster_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.monster
ADD CONSTRAINT monster_pkey PRIMARY KEY (id);
--
-- TOC entry 2887 (class 2606 OID 24728)
-- Name: play_status play_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.play_status
ADD CONSTRAINT play_status_pkey PRIMARY KEY (id);
--
-- TOC entry 2883 (class 2606 OID 24706)
-- Name: potion potion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.potion
ADD CONSTRAINT potion_pkey PRIMARY KEY (id);
--
-- TOC entry 2879 (class 2606 OID 24687)
-- Name: proficience proficience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.proficience
ADD CONSTRAINT proficience_pkey PRIMARY KEY (id);
--
-- TOC entry 2895 (class 2606 OID 24714)
-- Name: adventure adventure_idmonster_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.adventure
ADD CONSTRAINT adventure_idmonster_fkey FOREIGN KEY (idmonster) REFERENCES public.monster(id);
--
-- TOC entry 2907 (class 2606 OID 24824)
-- Name: aventure_monsters aventure_monsters_monsterid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.aventure_monsters
ADD CONSTRAINT aventure_monsters_monsterid_fkey FOREIGN KEY (monsterid) REFERENCES public.monster(id);
--
-- TOC entry 2908 (class 2606 OID 24829)
-- Name: aventure_monsters aventure_monsters_monsterid_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.aventure_monsters
ADD CONSTRAINT aventure_monsters_monsterid_fkey1 FOREIGN KEY (monsterid) REFERENCES public.adventure(id);
--
-- TOC entry 2900 (class 2606 OID 24756)
-- Name: hero hero_iddamageproficience_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_iddamageproficience_fkey FOREIGN KEY (iddamageproficience) REFERENCES public.proficience(id);
--
-- TOC entry 2901 (class 2606 OID 24761)
-- Name: hero hero_iddefenceproficience_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_iddefenceproficience_fkey FOREIGN KEY (iddefenceproficience) REFERENCES public.proficience(id);
--
-- TOC entry 2902 (class 2606 OID 24766)
-- Name: hero hero_idheroclass_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_idheroclass_fkey FOREIGN KEY (idheroclass) REFERENCES public.heroclass(id);
--
-- TOC entry 2899 (class 2606 OID 24751)
-- Name: hero hero_idplaystatus_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_idplaystatus_fkey FOREIGN KEY (idplaystatus) REFERENCES public.play_status(id);
--
-- TOC entry 2897 (class 2606 OID 24741)
-- Name: hero hero_idshield_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_idshield_fkey FOREIGN KEY (idshield) REFERENCES public.equip(id);
--
-- TOC entry 2898 (class 2606 OID 24746)
-- Name: hero hero_idweapon_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.hero
ADD CONSTRAINT hero_idweapon_fkey FOREIGN KEY (idweapon) REFERENCES public.equip(id);
--
-- TOC entry 2905 (class 2606 OID 24795)
-- Name: inventory_equip inventory_equip_idequip_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.inventory_equip
ADD CONSTRAINT inventory_equip_idequip_fkey FOREIGN KEY (idequip) REFERENCES public.equip(id);
--
-- TOC entry 2906 (class 2606 OID 24800)
-- Name: inventory_equip inventory_equip_idhero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.inventory_equip
ADD CONSTRAINT inventory_equip_idhero_fkey FOREIGN KEY (idhero) REFERENCES public.hero(id);
--
-- TOC entry 2904 (class 2606 OID 24783)
-- Name: inventory_potion inventory_potion_idhero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.inventory_potion
ADD CONSTRAINT inventory_potion_idhero_fkey FOREIGN KEY (idhero) REFERENCES public.hero(id);
--
-- TOC entry 2903 (class 2606 OID 24778)
-- Name: inventory_potion inventory_potion_idpotion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.inventory_potion
ADD CONSTRAINT inventory_potion_idpotion_fkey FOREIGN KEY (idpotion) REFERENCES public.potion(id);
--
-- TOC entry 2894 (class 2606 OID 24695)
-- Name: monster monster_idequipdrop_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.monster
ADD CONSTRAINT monster_idequipdrop_fkey FOREIGN KEY (idequipdrop) REFERENCES public.equip(id);
--
-- TOC entry 2896 (class 2606 OID 24729)
-- Name: play_status play_status_idadventure_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE ONLY public.play_status
ADD CONSTRAINT play_status_idadventure_fkey FOREIGN KEY (idadventure) REFERENCES public.adventure(id);
-- Completed on 2021-04-18 20:01:56 UTC
--
-- PostgreSQL database dump complete
--