--
-- PostgreSQL database dump
--
-- Dumped from database version 11.1
-- Dumped by pg_dump version 11.1
-- Started on 2019-04-07 22:21:55
SET
    statement_timeout = 0;
SET
    lock_timeout = 0;
SET
    idle_in_transaction_session_timeout = 0;
SET
    client_encoding = 'UTF8';
SET
    standard_conforming_strings = on;
SELECT
    pg_catalog.set_config('search_path', '', false);
SET
    check_function_bodies = false;
SET
    client_min_messages = warning;
SET
    row_security = off;
SET
    default_tablespace = '';
SET
    default_with_oids = false;--
    -- TOC entry 209 (class 1259 OID 61308)
    -- Name: adventure; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.adventure (
        id bigint NOT NULL,
        level integer NOT NULL,
        name character(40) NOT NULL,
        idmonster bigint NOT NULL
    );
ALTER TABLE
    public.adventure OWNER TO postgres;--
    -- TOC entry 208 (class 1259 OID 61306)
    -- Name: adventure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.adventure
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.adventure_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 201 (class 1259 OID 61275)
    -- Name: equip; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.equip (
        id bigint NOT NULL,
        name character(30) NOT NULL,
        level integer NOT NULL,
        type character(20) NOT NULL,
        defence integer,
        damage integer,
        price integer NOT NULL
    );
ALTER TABLE
    public.equip OWNER TO postgres;--
    -- TOC entry 200 (class 1259 OID 61273)
    -- Name: equip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.equip
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.equip_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 213 (class 1259 OID 61335)
    -- Name: hero; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.hero (
        id bigint NOT NULL,
        name character(30) NOT NULL,
        level integer NOT NULL,
        hptotal integer NOT NULL,
        hpactual integer NOT NULL,
        xp integer NOT NULL,
        levelmaxxp integer NOT NULL,
        gold integer NOT NULL,
        deaths integer NOT NULL,
        monsterskilled integer NOT NULL,
        idshield bigint,
        idweapon bigint,
        idplaystatus bigint,
        iddamageproficience bigint,
        iddefenceproficience bigint,
        idheroclass bigint
    );
ALTER TABLE
    public.hero OWNER TO postgres;--
    -- TOC entry 212 (class 1259 OID 61333)
    -- Name: hero_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.hero
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.hero_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 199 (class 1259 OID 61268)
    -- Name: heroclass; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.heroclass (
        id bigint NOT NULL,
        name character(30) NOT NULL,
        damagebuff integer NOT NULL,
        shieldbuff integer NOT NULL,
        hpbuff integer NOT NULL,
        goldbuff integer NOT NULL,
        expbuff integer NOT NULL,
        attackspeedbuff integer NOT NULL
    );
ALTER TABLE
    public.heroclass OWNER TO postgres;--
    -- TOC entry 198 (class 1259 OID 61266)
    -- Name: heroclass_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.heroclass
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.heroclass_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 217 (class 1259 OID 61389)
    -- Name: inventory_equip; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.inventory_equip (
        id bigint NOT NULL,
        idhero bigint,
        equiped boolean NOT NULL,
        idequip bigint
    );
ALTER TABLE
    public.inventory_equip OWNER TO postgres;--
    -- TOC entry 216 (class 1259 OID 61387)
    -- Name: inventory_equip_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.inventory_equip
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.inventory_equip_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 215 (class 1259 OID 61372)
    -- Name: inventory_potion; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.inventory_potion (
        id bigint NOT NULL,
        idhero bigint,
        amount integer NOT NULL,
        idpotion bigint
    );
ALTER TABLE
    public.inventory_potion OWNER TO postgres;--
    -- TOC entry 214 (class 1259 OID 61370)
    -- Name: inventory_potion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.inventory_potion
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.inventory_potion_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 197 (class 1259 OID 57536)
    -- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.migrations (
        id integer NOT NULL,
        "timestamp" bigint NOT NULL,
        name character varying NOT NULL
    );
ALTER TABLE
    public.migrations OWNER TO postgres;--
    -- TOC entry 196 (class 1259 OID 57534)
    -- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
    CREATE SEQUENCE public.migrations_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE
    public.migrations_id_seq OWNER TO postgres;--
    -- TOC entry 2933 (class 0 OID 0)
    -- Dependencies: 196
    -- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
    --
    ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;--
    -- TOC entry 205 (class 1259 OID 61289)
    -- Name: monster; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.monster (
        id bigint NOT NULL,
        name character(30) NOT NULL,
        level integer NOT NULL,
        damage integer NOT NULL,
        hp integer NOT NULL,
        defence integer NOT NULL,
        givedxp integer NOT NULL,
        givedgold integer NOT NULL,
        equipdropchance integer NOT NULL,
        idequipdrop bigint
    );
ALTER TABLE
    public.monster OWNER TO postgres;--
    -- TOC entry 204 (class 1259 OID 61287)
    -- Name: monster_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.monster
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.monster_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 211 (class 1259 OID 61320)
    -- Name: play_status; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.play_status (
        id bigint NOT NULL,
        task character(30),
        gold integer NOT NULL,
        monsterskilled integer DEFAULT 0 NOT NULL,
        exp integer DEFAULT 0 NOT NULL,
        timestarted integer DEFAULT 0 NOT NULL,
        idadventure bigint
    );
ALTER TABLE
    public.play_status OWNER TO postgres;--
    -- TOC entry 210 (class 1259 OID 61318)
    -- Name: play_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.play_status
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.play_status_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 207 (class 1259 OID 61301)
    -- Name: potion; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.potion (
        id bigint NOT NULL,
        name character(50) NOT NULL,
        price integer NOT NULL,
        hpheal integer NOT NULL
    );
ALTER TABLE
    public.potion OWNER TO postgres;--
    -- TOC entry 206 (class 1259 OID 61299)
    -- Name: potion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.potion
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.potion_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 203 (class 1259 OID 61282)
    -- Name: proficience; Type: TABLE; Schema: public; Owner: postgres
    --
    CREATE TABLE public.proficience (
        id bigint NOT NULL,
        level integer NOT NULL,
        xp integer NOT NULL,
        levelmaxxp integer NOT NULL
    );
ALTER TABLE
    public.proficience OWNER TO postgres;--
    -- TOC entry 202 (class 1259 OID 61280)
    -- Name: proficience_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --
ALTER TABLE
    public.proficience
ALTER COLUMN
    id
ADD
    GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.proficience_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );--
    -- TOC entry 2746 (class 2604 OID 57539)
    -- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.migrations
ALTER COLUMN
    id
SET
    DEFAULT nextval('public.migrations_id_seq' :: regclass);--
    -- TOC entry 2919 (class 0 OID 61308)
    -- Dependencies: 209
    -- Data for Name: adventure; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.adventure (id, level, name, idmonster)
FROM
    stdin;\.--
    -- TOC entry 2911 (class 0 OID 61275)
    -- Dependencies: 201
    -- Data for Name: equip; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.equip (id, name, level, type, defence, damage, price)
FROM
    stdin;1 wood sword 1 weapon \ N 1 1 2 wood shield 1 shield 1 \ N 1 \.--
    -- TOC entry 2923 (class 0 OID 61335)
    -- Dependencies: 213
    -- Data for Name: hero; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.hero (
        id,
        name,
        level,
        hptotal,
        hpactual,
        xp,
        levelmaxxp,
        gold,
        deaths,
        monsterskilled,
        idshield,
        idweapon,
        idplaystatus,
        iddamageproficience,
        iddefenceproficience,
        idheroclass
    )
FROM
    stdin;262162779987902460 lucas 1 100 100 0 100 0 0 0 2 1 1 2 1 1 \.--
    -- TOC entry 2909 (class 0 OID 61268)
    -- Dependencies: 199
    -- Data for Name: heroclass; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.heroclass (
        id,
        name,
        damagebuff,
        shieldbuff,
        hpbuff,
        goldbuff,
        expbuff,
        attackspeedbuff
    )
FROM
    stdin;1 Begginner 0 0 0 0 0 0 2 Warrior 0 0 5 0 0 0 3 Mage 0 0 0 0 3 0 4 Thief 0 0 0 1 0 0 5 Archer 0 0 5 0 0 0 6 Kinight 0 0 10 1 0 0 7 Paladin 5 0 5 1 0 0 8 Necro 0 0 5 0 0 0 9 Ladin 0 0 5 1 0 0 10 Ninja 5 0 0 1 0 0 11 Hunter 10 0 0 1 0 1 12 Trickster 5 0 5 1 0 1 \.--
    -- TOC entry 2927 (class 0 OID 61389)
    -- Dependencies: 217
    -- Data for Name: inventory_equip; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.inventory_equip (id, idhero, equiped, idequip)
FROM
    stdin;1 262162779987902460 f 1 2 262162779987902460 f \ N \.--
    -- TOC entry 2925 (class 0 OID 61372)
    -- Dependencies: 215
    -- Data for Name: inventory_potion; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.inventory_potion (id, idhero, amount, idpotion)
FROM
    stdin;\.--
    -- TOC entry 2907 (class 0 OID 57536)
    -- Dependencies: 197
    -- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.migrations (id, "timestamp", name)
FROM
    stdin;85 1548891232589 Migration1548891232589 86 1550502138205 Migration1550502138205 87 1553732225197 BaseEquips1553732225197 \.--
    -- TOC entry 2915 (class 0 OID 61289)
    -- Dependencies: 205
    -- Data for Name: monster; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.monster (
        id,
        name,
        level,
        damage,
        hp,
        defence,
        givedxp,
        givedgold,
        equipdropchance,
        idequipdrop
    )
FROM
    stdin;\.--
    -- TOC entry 2921 (class 0 OID 61320)
    -- Dependencies: 211
    -- Data for Name: play_status; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.play_status (
        id,
        task,
        gold,
        monsterskilled,
        exp,
        timestarted,
        idadventure
    )
FROM
    stdin;1 \ N 0 0 0 0 \ N 2 \ N 0 0 0 0 \ N \.--
    -- TOC entry 2917 (class 0 OID 61301)
    -- Dependencies: 207
    -- Data for Name: potion; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.potion (id, name, price, hpheal)
FROM
    stdin;\.--
    -- TOC entry 2913 (class 0 OID 61282)
    -- Dependencies: 203
    -- Data for Name: proficience; Type: TABLE DATA; Schema: public; Owner: postgres
    --
    COPY public.proficience (id, level, xp, levelmaxxp)
FROM
    stdin;1 1 0 205 2 1 0 205 3 1 0 205 4 1 0 205 \.--
    -- TOC entry 2934 (class 0 OID 0)
    -- Dependencies: 208
    -- Name: adventure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.adventure_id_seq', 1, false);--
    -- TOC entry 2935 (class 0 OID 0)
    -- Dependencies: 200
    -- Name: equip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.equip_id_seq', 2, true);--
    -- TOC entry 2936 (class 0 OID 0)
    -- Dependencies: 212
    -- Name: hero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.hero_id_seq', 1, false);--
    -- TOC entry 2937 (class 0 OID 0)
    -- Dependencies: 198
    -- Name: heroclass_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.heroclass_id_seq', 12, true);--
    -- TOC entry 2938 (class 0 OID 0)
    -- Dependencies: 216
    -- Name: inventory_equip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.inventory_equip_id_seq', 2, true);--
    -- TOC entry 2939 (class 0 OID 0)
    -- Dependencies: 214
    -- Name: inventory_potion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.inventory_potion_id_seq', 1, false);--
    -- TOC entry 2940 (class 0 OID 0)
    -- Dependencies: 196
    -- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.migrations_id_seq', 87, true);--
    -- TOC entry 2941 (class 0 OID 0)
    -- Dependencies: 204
    -- Name: monster_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.monster_id_seq', 1, false);--
    -- TOC entry 2942 (class 0 OID 0)
    -- Dependencies: 210
    -- Name: play_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.play_status_id_seq', 2, true);--
    -- TOC entry 2943 (class 0 OID 0)
    -- Dependencies: 206
    -- Name: potion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.potion_id_seq', 1, false);--
    -- TOC entry 2944 (class 0 OID 0)
    -- Dependencies: 202
    -- Name: proficience_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --
SELECT
    pg_catalog.setval('public.proficience_id_seq', 4, true);--
    -- TOC entry 2751 (class 2606 OID 57544)
    -- Name: migrations PK_8c82d7f526340ab734260ea46be; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.migrations
ADD
    CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id);--
    -- TOC entry 2763 (class 2606 OID 61312)
    -- Name: adventure adventure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.adventure
ADD
    CONSTRAINT adventure_pkey PRIMARY KEY (id);--
    -- TOC entry 2755 (class 2606 OID 61279)
    -- Name: equip equip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.equip
ADD
    CONSTRAINT equip_pkey PRIMARY KEY (id);--
    -- TOC entry 2767 (class 2606 OID 61339)
    -- Name: hero hero_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_pkey PRIMARY KEY (id);--
    -- TOC entry 2753 (class 2606 OID 61272)
    -- Name: heroclass heroclass_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.heroclass
ADD
    CONSTRAINT heroclass_pkey PRIMARY KEY (id);--
    -- TOC entry 2771 (class 2606 OID 61393)
    -- Name: inventory_equip inventory_equip_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.inventory_equip
ADD
    CONSTRAINT inventory_equip_pkey PRIMARY KEY (id);--
    -- TOC entry 2769 (class 2606 OID 61376)
    -- Name: inventory_potion inventory_potion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.inventory_potion
ADD
    CONSTRAINT inventory_potion_pkey PRIMARY KEY (id);--
    -- TOC entry 2759 (class 2606 OID 61293)
    -- Name: monster monster_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.monster
ADD
    CONSTRAINT monster_pkey PRIMARY KEY (id);--
    -- TOC entry 2765 (class 2606 OID 61327)
    -- Name: play_status play_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.play_status
ADD
    CONSTRAINT play_status_pkey PRIMARY KEY (id);--
    -- TOC entry 2761 (class 2606 OID 61305)
    -- Name: potion potion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.potion
ADD
    CONSTRAINT potion_pkey PRIMARY KEY (id);--
    -- TOC entry 2757 (class 2606 OID 61286)
    -- Name: proficience proficience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.proficience
ADD
    CONSTRAINT proficience_pkey PRIMARY KEY (id);--
    -- TOC entry 2773 (class 2606 OID 61313)
    -- Name: adventure adventure_idmonster_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.adventure
ADD
    CONSTRAINT adventure_idmonster_fkey FOREIGN KEY (idmonster) REFERENCES public.monster(id);--
    -- TOC entry 2778 (class 2606 OID 61355)
    -- Name: hero hero_iddamageproficience_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_iddamageproficience_fkey FOREIGN KEY (iddamageproficience) REFERENCES public.proficience(id);--
    -- TOC entry 2779 (class 2606 OID 61360)
    -- Name: hero hero_iddefenceproficience_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_iddefenceproficience_fkey FOREIGN KEY (iddefenceproficience) REFERENCES public.proficience(id);--
    -- TOC entry 2780 (class 2606 OID 61365)
    -- Name: hero hero_idheroclass_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_idheroclass_fkey FOREIGN KEY (idheroclass) REFERENCES public.heroclass(id);--
    -- TOC entry 2777 (class 2606 OID 61350)
    -- Name: hero hero_idplaystatus_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_idplaystatus_fkey FOREIGN KEY (idplaystatus) REFERENCES public.play_status(id);--
    -- TOC entry 2775 (class 2606 OID 61340)
    -- Name: hero hero_idshield_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_idshield_fkey FOREIGN KEY (idshield) REFERENCES public.equip(id);--
    -- TOC entry 2776 (class 2606 OID 61345)
    -- Name: hero hero_idweapon_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.hero
ADD
    CONSTRAINT hero_idweapon_fkey FOREIGN KEY (idweapon) REFERENCES public.equip(id);--
    -- TOC entry 2783 (class 2606 OID 61394)
    -- Name: inventory_equip inventory_equip_idequip_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.inventory_equip
ADD
    CONSTRAINT inventory_equip_idequip_fkey FOREIGN KEY (idequip) REFERENCES public.equip(id);--
    -- TOC entry 2784 (class 2606 OID 61399)
    -- Name: inventory_equip inventory_equip_idhero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.inventory_equip
ADD
    CONSTRAINT inventory_equip_idhero_fkey FOREIGN KEY (idhero) REFERENCES public.hero(id);--
    -- TOC entry 2782 (class 2606 OID 61382)
    -- Name: inventory_potion inventory_potion_idhero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.inventory_potion
ADD
    CONSTRAINT inventory_potion_idhero_fkey FOREIGN KEY (idhero) REFERENCES public.hero(id);--
    -- TOC entry 2781 (class 2606 OID 61377)
    -- Name: inventory_potion inventory_potion_idpotion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.inventory_potion
ADD
    CONSTRAINT inventory_potion_idpotion_fkey FOREIGN KEY (idpotion) REFERENCES public.potion(id);--
    -- TOC entry 2772 (class 2606 OID 61294)
    -- Name: monster monster_idequipdrop_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.monster
ADD
    CONSTRAINT monster_idequipdrop_fkey FOREIGN KEY (idequipdrop) REFERENCES public.equip(id);--
    -- TOC entry 2774 (class 2606 OID 61328)
    -- Name: play_status play_status_idadventure_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --
ALTER TABLE
    ONLY public.play_status
ADD
    CONSTRAINT play_status_idadventure_fkey FOREIGN KEY (idadventure) REFERENCES public.adventure(id);-- Completed on 2019-04-07 22:21:57
    --
    -- PostgreSQL database dump complete
    --