version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    paralelism: 4
    steps:
      - checkout
      - run:
          name: Update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Project
          command: npm run build
  test:
    docker:
      - image: circleci/node:10
      # Service container image available at `host: localhost`
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: testdb
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install postgree's server
          command: sudo apt install -y postgresql-client || true
      - run:
          name: Migrate database
          command: npm run migrations
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
