name: e2e CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Create .env file
        run: |
          cd ./e2e
          touch .env
          echo CORDE_TEST_TOKEN_LINUX=${{ secrets.CORDE_TEST_TOKEN_LINUX }} > .env
          echo BOT_PREFIX=${{ secrets.BOT_PREFIX }} >> .env
          echo TIME_OUT=${{ secrets.TIME_OUT }} >> .env
          echo BOT_TEST_ID_LINUX=${{ secrets.BOT_TEST_ID_LINUX }} >> .env
          echo CHANNEL_ID_LINUX=${{ secrets.CHANNEL_ID_LINUX }} >> .env
          echo GUILD_ID_LINUX=${{ secrets.GUILD_ID_LINUX }} >> .env
          echo BOT_TEST_TOKEN_LINUX=${{ secrets.BOT_TEST_TOKEN_LINUX }} >> .env
          cd ..

      - name: Run e2e
        run: yarn e2e linux

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Create .env file
        run: |
          cd ./e2e
          echo CORDE_TEST_TOKEN_WINDOWS=${{ secrets.CORDE_TEST_TOKEN_WINDOWS }} > .env
          echo BOT_PREFIX=${{ secrets.BOT_PREFIX }} >> .env
          echo TIME_OUT=${{ secrets.TIME_OUT }} >> .env
          echo BOT_TEST_ID_WINDOWS=${{ secrets.BOT_TEST_ID_WINDOWS }} >> .env
          echo CHANNEL_ID_WINDOWS=${{ secrets.CHANNEL_ID_WINDOWS }} >> .env
          echo GUILD_ID_WINDOWS=${{ secrets.GUILD_ID_WINDOWS }} >> .env
          echo BOT_TEST_TOKEN_WINDOWS=${{ secrets.BOT_TEST_TOKEN_WINDOWS }} >> .env
          cd ..

      - name: Run e2e
        run: yarn e2e windows

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Create .env file
        run: |
          cd ./e2e
          touch .env
          echo CORDE_TEST_TOKEN_MAC=${{ secrets.CORDE_TEST_TOKEN_MAC }} > .env
          echo BOT_PREFIX=${{ secrets.BOT_PREFIX }} >> .env
          echo TIME_OUT=${{ secrets.TIME_OUT }} >> .env
          echo BOT_TEST_ID_MAC=${{ secrets.BOT_TEST_ID_MAC }} >> .env
          echo CHANNEL_ID_MAC=${{ secrets.CHANNEL_ID_MAC }} >> .env
          echo GUILD_ID_MAC=${{ secrets.GUILD_ID_MAC }} >> .env
          echo BOT_TEST_TOKEN_MAC=${{ secrets.BOT_TEST_TOKEN_MAC }} >> .env
          cd ..

      - name: Run e2e
        run: yarn e2e mac
